# Generated by Django 4.2.16 on 2024-10-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tunnelvision", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitoringconfig",
            name="frequency",
            field=models.IntegerField(default=60),
        ),
    ]
